# Generated by Django 3.1.6 on 2021-11-25 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_favorite'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Favorite',
        ),
    ]
