# Generated by Django 3.1.6 on 2021-12-07 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_message'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['created']},
        ),
    ]
