# Generated by Django 3.1.6 on 2021-11-22 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project_feattured_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='feattured_image',
            new_name='featured_image',
        ),
    ]
